# Site settings
title: Alexandros Polyzoidis
description: "Data Scientist with a robust background in B2B technology sales and a Master's Degree in Logistics & Supply Chain Management. Leveraging analytical prowess to drive data-driven decision-making."

# Build settings
theme: jekyll-theme-minimal
## remote_theme: pages-themes/minimal@v2.0

# Plugins
#plugins:
#jekyll-remote-theme

# Personal and Social Links
linkedin_url: https://www.linkedin.com/in/alexandrospolyzoidis/
github_url: https://github.com/AlexandrosPol
email: apolyzoidis@hotmail.com

# Optional features
show_downloads: true
google_analytics: UA-000000-2 # Replace with your Google Analytics tracking ID if you have one

# Image and Logo
logo: /assets/img/Proff_photo.jpg # Make sure the path to your profile picture is correct

# Other configurations
markdown: kramdown
permalink: pretty
