title: Alexandros Polyzoidis # your name (or website title) here
logo: /assets/img/Proff_photo.jpg # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced Sales Specialist at Cyclopt with a robust background in B2B technology sales and a Master's Degree in Logistics & Supply Chain Management. Former Transportation Manager in the 3PL sector with a strategic mindset and operational prowess.  
  <br><br>
  Currently enhancing skills in Data Science and Machine Learning. Aiming to merge strategic insights from logistics with advanced analytics expertise. Excited to contribute to data-driven solutions in the evolving landscape of technology.
  <br><br>
  <a href="https://www.linkedin.com/in/alexandrospolyzoidis/">View My LinkedIn Profile</a> 
# show_downloads: true
# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
