title: "Alexandros Polyzoidis - Portfolio"
description: "Portfolio showcasing my data science and machine learning projects."
remote_theme: "mmistakes/minimal-mistakes"
markdown: kramdown
permalink: pretty
